services:

  # docker exec -it mysql-server-1 bash  
  mysql-server-1:
    image: mysql/mysql-server
    container_name: mysql-server-1
    environment: 
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      timeout: 20s
      retries: 10
    ports:
      - "3301:3306"
    volumes: 
      - ./data/server-1:/var/lib/mysql      
    restart: always
    command: [
      "mysqld",
      "--server_id=1",
      "--mysqlx=ON",
      "--binlog_checksum=NONE",
      "--gtid_mode=ON",
      "--enforce_gtid_consistency=ON",
      "--log_bin",
      "--log_slave_updates=ON",
      "--master_info_repository=TABLE",
      "--relay_log_info_repository=TABLE",
      "--transaction_write_set_extraction=XXHASH64",
      "--user=root",
      "--skip-host-cache",
      "--skip-name-resolve", 
      "--default_authentication_plugin=mysql_native_password",
      "--binlog_transaction_dependency_tracking=WRITESET"]

  mysql-server-2:
    image: mysql/mysql-server
    container_name: mysql-server-2
    environment: 
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      timeout: 20s
      retries: 10
    ports:
      - "3302:3306"
    volumes: 
      - ./data/server-2:/var/lib/mysql      
    restart: always
    command: [
      "mysqld",
      "--server_id=2",
      "--mysqlx=ON",
      "--binlog_checksum=NONE",
      "--gtid_mode=ON",
      "--enforce_gtid_consistency=ON",
      "--log_bin",
      "--log_slave_updates=ON",
      "--master_info_repository=TABLE",
      "--relay_log_info_repository=TABLE",
      "--transaction_write_set_extraction=XXHASH64",
      "--user=root",
      "--skip-host-cache",
      "--skip-name-resolve", 
      "--default_authentication_plugin=mysql_native_password",
      "--binlog_transaction_dependency_tracking=WRITESET"]

  mysql-server-3:
    image: mysql/mysql-server
    container_name: mysql-server-3
    user: root
    environment: 
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      timeout: 20s
      retries: 10
    ports:
      - "3303:3306"
    volumes: 
      - ./data/server-3:/var/lib/mysql      
    restart: always
    command: [
      "mysqld",
      "--server_id=3",
      "--mysqlx=ON",
      "--binlog_checksum=NONE",
      "--gtid_mode=ON",
      "--enforce_gtid_consistency=ON",
      "--log_bin",
      "--log_slave_updates=ON",
      "--master_info_repository=TABLE",
      "--relay_log_info_repository=TABLE",
      "--transaction_write_set_extraction=XXHASH64",
      "--user=root",
      "--skip-host-cache",
      "--skip-name-resolve", 
      "--default_authentication_plugin=mysql_native_password",
      "--binlog_transaction_dependency_tracking=WRITESET"]
  mysql-router:
    image: mysql/mysql-router
    container_name: mysql-router
    environment:
      MYSQL_HOST: 'mysql-server-1'
      MYSQL_PORT: 3306
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_INNODB_NUM_MEMBERS: 3
      MYSQL_CREATE_ROUTER_USER: 0
      # MYSQL_ROUTER_BOOTSTRAP_EXTRA_OPTIONS="--extra-config /etc/mysqlrouter-custom/mysqlrouter.conf --ssl-mode DISABLED --client-ssl-mode DISABLED"
      # MYSQL_ROUTER_BOOTSTRAP_EXTRA_OPTIONS="--force --extra-config /etc/mysqlrouter-custom/mysqlrouter.conf --client-ssl-mode PASSTHROUGH --server-ssl-ca /etc/mysqlrouter-custom/certificates/ca.pem --client-ssl-cert /etc/mysqlrouter-custom/certificates/server-cert.pem --client-ssl-key /etc/mysqlrouter-custom/certificates/server-key.pem"
    ports:
      - "8088:8088"
      - "6446:6446"
    volumes:
      - ./docker/mysql-router:/etc/mysqlrouter-custom
    depends_on:
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3
      - mysql-shell
    restart: on-failure

  mysql-shell:
    image: norpac/mysql-shell
    container_name: mysql-shell
    # For interactive Mode. Used with: docker exec -it mysql-shell bash
    # entrypoint: tail -f /dev/null
    environment:
      # TODO: Use in mysqlsh
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_HOST_1=mysql-server-1
      - MYSQL_HOST_2=mysql-server-2
      - MYSQL_HOST_3=mysql-server-3
      - MYSQL_PORT_1=3306
      - MYSQL_PORT_2=3306
      - MYSQL_PORT_3=3306
    volumes:
        - ./docker/scripts:/scripts
    depends_on:
      mysql-server-1:
        condition: service_healthy
      mysql-server-2:
        condition: service_healthy
      mysql-server-3:
        condition: service_healthy