version: "3.7"

services:

  mrs-server-1:
    env_file:
      - ./docker/mysql-server.env
    image: mysql/mysql-server:8.0.12
    user: root
    ports:
      - "3301:3306"
    command: ["mysqld","--server_id=1","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=root","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]

  mrs-server-2:
    env_file:
      - ./docker/mysql-server.env
    image: mysql/mysql-server:8.0.12
    user: root
    ports:
      - "3302:3306"
    command: ["mysqld","--server_id=2","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=root","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]

  mrs-server-3:
    env_file:
      - ./docker/mysql-server.env
    image: mysql/mysql-server:8.0.12
    user: root
    ports:
      - "3303:3306"
    command: ["mysqld","--server_id=3","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=root","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
  
  mrs-router:
    image: mysql/mysql-router:8.0
    container_name: mrs-router-container
    user: root
    env_file:
      - ./docker/mysql-router.env
    ports:
      - "8088:8088"
      - "6446:6446"
    volumes:
      - ./docker/mysql-router:/etc/mysqlrouter-custom
    depends_on:
      - mrs-server-1
      - mrs-server-2
      - mrs-server-3
      - mrs-shell
    restart: on-failure

  mrs-shell:
    env_file:
      - ./docker/mysql-shell.env
    image: neumayer/mysql-shell-batch
    volumes:
        - ./docker/scripts:/scripts
    depends_on:
      - mrs-server-1
      - mrs-server-2
      - mrs-server-3